# This file is completely useless, so if you're trying to steal this plugin, good luck trying to edit obfuscated code ;))

# You can try changing this, but it won't do anything.
CliftonCity: Best NA

# Would you like to enable L dance?
L_Dance_Enabled: true

# Delected was here