package main;

import Storage.Cards;
import Storage.Companies;
import commands.CardsManager;
import commands.CompaniesManager;
import commands.Reload;
import org.bukkit.event.Listener;
import org.bukkit.plugin.java.JavaPlugin;

import java.io.IOException;
import java.util.Objects;


public class CFTapPlus extends JavaPlugin implements Listener {
    public static JavaPlugin plugin;

    public static JavaPlugin getPlugin() {
        return plugin;
    }

    public void onEnable(){
        plugin = this;
        // config.yml (100% working)
        saveDefaultConfig();
        // companies.yml
        try {
            Companies.setup();
            Companies.get().options().copyHeader(true).header("Do not edit this file unless you know what you are doing. Otherwise, please use commands.");
            Companies.get().options().copyDefaults(true);
            Companies.save();
        } catch (IOException e) {
            e.printStackTrace();
            System.out.println("[main.CFTapPlus] Couldn't create the companies.yml file!");
        }
        // cards.yml
        try {
            Cards.setup();
            Cards.get().options().copyHeader(true).header("Do not edit this file unless you know what you are doing. Otherwise, please use commands.");
            Cards.get().options().copyDefaults(true);
            Cards.save();
        } catch (IOException e) {
            e.printStackTrace();
            System.out.println("[main.CFTapPlus] Couldn't create the cards.yml file!");
        }
        // commands
        Objects.requireNonNull(getCommand("company")).setExecutor(new CompaniesManager());
        Objects.requireNonNull(getCommand("card")).setExecutor(new CardsManager());
        Objects.requireNonNull(getCommand("cftpreload")).setExecutor(new Reload());
        // events
    }
}
